---
- name: NextCloud | Install PHP7 repositories
  yum:
    name:
      - centos-release-scl
      - epel-release
    state: present

- name: NextCloud | Install PHP
  yum:
    name:
      - centos-release-scl
      - rh-php72
      - rh-php72-php
      - rh-php72-php-gd
      - rh-php72-php-mbstring
      - rh-php72-php-intl
      - rh-php72-php-pecl-apcu
      - rh-php72-php-mysqlnd
      - rh-php72-php-pecl-redis
      - rh-php72-php-opcache
      - rh-php72-php-imagick
    state: present

# Test this before using in production
- name: NextCloud | Create symlinks
  file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
    force: yes
  with_items:
    - { dest: /opt/rh/httpd24/root/etc/httpd/conf.d/rh-php72-php.conf, src: /etc/httpd/conf.d }
    - { dest: /opt/rh/httpd24/root/etc/httpd/conf.modules.d/15-rh-php72-php.conf, src: /etc/httpd/conf.modules.d }
    - { dest: /opt/rh/httpd24/root/etc/httpd/modules/librh-php72-php7.so, src: /etc/httpd/modules }
    - { dest: /opt/rh/rh-php72/root/bin/php, src: /usr/bin/php }
