---
# handlers file for digistro-nextcloud
- name: restart apache
  service:
    name: httpd
    state: restarted

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: disable selinux
  selinux:
    state: disabled
